<?php
/**
 * ListingUpdateDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bloom API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ListingUpdateDtoTest Class Doc Comment
 *
 * @category    Class
 * @description ListingUpdateDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ListingUpdateDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ListingUpdateDto"
     */
    public function testListingUpdateDto()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "display_waitlist_size"
     */
    public function testPropertyDisplayWaitlistSize()
    {
    }

    /**
     * Test attribute "csv_formatting_type"
     */
    public function testPropertyCsvFormattingType()
    {
    }

    /**
     * Test attribute "county_code"
     */
    public function testPropertyCountyCode()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "preferences"
     */
    public function testPropertyPreferences()
    {
    }

    /**
     * Test attribute "property"
     */
    public function testPropertyProperty()
    {
    }

    /**
     * Test attribute "application_address"
     */
    public function testPropertyApplicationAddress()
    {
    }

    /**
     * Test attribute "application_pick_up_address"
     */
    public function testPropertyApplicationPickUpAddress()
    {
    }

    /**
     * Test attribute "leasing_agent_address"
     */
    public function testPropertyLeasingAgentAddress()
    {
    }

    /**
     * Test attribute "leasing_agents"
     */
    public function testPropertyLeasingAgents()
    {
    }

    /**
     * Test attribute "application_methods"
     */
    public function testPropertyApplicationMethods()
    {
    }

    /**
     * Test attribute "assets"
     */
    public function testPropertyAssets()
    {
    }

    /**
     * Test attribute "events"
     */
    public function testPropertyEvents()
    {
    }

    /**
     * Test attribute "application_due_date"
     */
    public function testPropertyApplicationDueDate()
    {
    }

    /**
     * Test attribute "application_open_date"
     */
    public function testPropertyApplicationOpenDate()
    {
    }

    /**
     * Test attribute "application_fee"
     */
    public function testPropertyApplicationFee()
    {
    }

    /**
     * Test attribute "application_organization"
     */
    public function testPropertyApplicationOrganization()
    {
    }

    /**
     * Test attribute "application_pick_up_address_office_hours"
     */
    public function testPropertyApplicationPickUpAddressOfficeHours()
    {
    }

    /**
     * Test attribute "building_selection_criteria"
     */
    public function testPropertyBuildingSelectionCriteria()
    {
    }

    /**
     * Test attribute "costs_not_included"
     */
    public function testPropertyCostsNotIncluded()
    {
    }

    /**
     * Test attribute "credit_history"
     */
    public function testPropertyCreditHistory()
    {
    }

    /**
     * Test attribute "criminal_background"
     */
    public function testPropertyCriminalBackground()
    {
    }

    /**
     * Test attribute "deposit_min"
     */
    public function testPropertyDepositMin()
    {
    }

    /**
     * Test attribute "deposit_max"
     */
    public function testPropertyDepositMax()
    {
    }

    /**
     * Test attribute "disable_units_accordion"
     */
    public function testPropertyDisableUnitsAccordion()
    {
    }

    /**
     * Test attribute "leasing_agent_email"
     */
    public function testPropertyLeasingAgentEmail()
    {
    }

    /**
     * Test attribute "leasing_agent_name"
     */
    public function testPropertyLeasingAgentName()
    {
    }

    /**
     * Test attribute "leasing_agent_office_hours"
     */
    public function testPropertyLeasingAgentOfficeHours()
    {
    }

    /**
     * Test attribute "leasing_agent_phone"
     */
    public function testPropertyLeasingAgentPhone()
    {
    }

    /**
     * Test attribute "leasing_agent_title"
     */
    public function testPropertyLeasingAgentTitle()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "postmarked_applications_received_by_date"
     */
    public function testPropertyPostmarkedApplicationsReceivedByDate()
    {
    }

    /**
     * Test attribute "program_rules"
     */
    public function testPropertyProgramRules()
    {
    }

    /**
     * Test attribute "rental_assistance"
     */
    public function testPropertyRentalAssistance()
    {
    }

    /**
     * Test attribute "rental_history"
     */
    public function testPropertyRentalHistory()
    {
    }

    /**
     * Test attribute "required_documents"
     */
    public function testPropertyRequiredDocuments()
    {
    }

    /**
     * Test attribute "special_notes"
     */
    public function testPropertySpecialNotes()
    {
    }

    /**
     * Test attribute "waitlist_current_size"
     */
    public function testPropertyWaitlistCurrentSize()
    {
    }

    /**
     * Test attribute "waitlist_max_size"
     */
    public function testPropertyWaitlistMaxSize()
    {
    }

    /**
     * Test attribute "what_to_expect"
     */
    public function testPropertyWhatToExpect()
    {
    }

    /**
     * Test attribute "application_config"
     */
    public function testPropertyApplicationConfig()
    {
    }
}
