<?php
/**
 * PropertyUpdateDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bloom API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PropertyUpdateDtoTest Class Doc Comment
 *
 * @category    Class
 * @description PropertyUpdateDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PropertyUpdateDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PropertyUpdateDto"
     */
    public function testPropertyUpdateDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "building_address"
     */
    public function testPropertyBuildingAddress()
    {
    }

    /**
     * Test attribute "units"
     */
    public function testPropertyUnits()
    {
    }

    /**
     * Test attribute "accessibility"
     */
    public function testPropertyAccessibility()
    {
    }

    /**
     * Test attribute "amenities"
     */
    public function testPropertyAmenities()
    {
    }

    /**
     * Test attribute "building_total_units"
     */
    public function testPropertyBuildingTotalUnits()
    {
    }

    /**
     * Test attribute "developer"
     */
    public function testPropertyDeveloper()
    {
    }

    /**
     * Test attribute "household_size_max"
     */
    public function testPropertyHouseholdSizeMax()
    {
    }

    /**
     * Test attribute "household_size_min"
     */
    public function testPropertyHouseholdSizeMin()
    {
    }

    /**
     * Test attribute "neighborhood"
     */
    public function testPropertyNeighborhood()
    {
    }

    /**
     * Test attribute "pet_policy"
     */
    public function testPropertyPetPolicy()
    {
    }

    /**
     * Test attribute "smoking_policy"
     */
    public function testPropertySmokingPolicy()
    {
    }

    /**
     * Test attribute "units_available"
     */
    public function testPropertyUnitsAvailable()
    {
    }

    /**
     * Test attribute "unit_amenities"
     */
    public function testPropertyUnitAmenities()
    {
    }

    /**
     * Test attribute "services_offered"
     */
    public function testPropertyServicesOffered()
    {
    }

    /**
     * Test attribute "year_built"
     */
    public function testPropertyYearBuilt()
    {
    }
}
