<?php
/**
 * UnitsSummarizedTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bloom API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UnitsSummarizedTest Class Doc Comment
 *
 * @category    Class
 * @description UnitsSummarized
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UnitsSummarizedTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UnitsSummarized"
     */
    public function testUnitsSummarized()
    {
    }

    /**
     * Test attribute "unit_types"
     */
    public function testPropertyUnitTypes()
    {
    }

    /**
     * Test attribute "reserved_types"
     */
    public function testPropertyReservedTypes()
    {
    }

    /**
     * Test attribute "priority_types"
     */
    public function testPropertyPriorityTypes()
    {
    }

    /**
     * Test attribute "ami_percentages"
     */
    public function testPropertyAmiPercentages()
    {
    }

    /**
     * Test attribute "by_unit_type"
     */
    public function testPropertyByUnitType()
    {
    }

    /**
     * Test attribute "by_non_reserved_unit_type"
     */
    public function testPropertyByNonReservedUnitType()
    {
    }

    /**
     * Test attribute "by_reserved_type"
     */
    public function testPropertyByReservedType()
    {
    }

    /**
     * Test attribute "by_ami"
     */
    public function testPropertyByAmi()
    {
    }

    /**
     * Test attribute "hmi"
     */
    public function testPropertyHmi()
    {
    }
}
