<?php
/**
 * UnitDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bloom API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UnitDtoTest Class Doc Comment
 *
 * @category    Class
 * @description UnitDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UnitDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UnitDto"
     */
    public function testUnitDto()
    {
    }

    /**
     * Test attribute "ami_chart"
     */
    public function testPropertyAmiChart()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "ami_percentage"
     */
    public function testPropertyAmiPercentage()
    {
    }

    /**
     * Test attribute "annual_income_min"
     */
    public function testPropertyAnnualIncomeMin()
    {
    }

    /**
     * Test attribute "monthly_income_min"
     */
    public function testPropertyMonthlyIncomeMin()
    {
    }

    /**
     * Test attribute "floor"
     */
    public function testPropertyFloor()
    {
    }

    /**
     * Test attribute "annual_income_max"
     */
    public function testPropertyAnnualIncomeMax()
    {
    }

    /**
     * Test attribute "max_occupancy"
     */
    public function testPropertyMaxOccupancy()
    {
    }

    /**
     * Test attribute "min_occupancy"
     */
    public function testPropertyMinOccupancy()
    {
    }

    /**
     * Test attribute "monthly_rent"
     */
    public function testPropertyMonthlyRent()
    {
    }

    /**
     * Test attribute "num_bathrooms"
     */
    public function testPropertyNumBathrooms()
    {
    }

    /**
     * Test attribute "num_bedrooms"
     */
    public function testPropertyNumBedrooms()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "priority_type"
     */
    public function testPropertyPriorityType()
    {
    }

    /**
     * Test attribute "reserved_type"
     */
    public function testPropertyReservedType()
    {
    }

    /**
     * Test attribute "sq_feet"
     */
    public function testPropertySqFeet()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "unit_type"
     */
    public function testPropertyUnitType()
    {
    }

    /**
     * Test attribute "monthly_rent_as_percent_of_income"
     */
    public function testPropertyMonthlyRentAsPercentOfIncome()
    {
    }

    /**
     * Test attribute "bmr_program_chart"
     */
    public function testPropertyBmrProgramChart()
    {
    }
}
