<?php
/**
 * UnitSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bloom API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UnitSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description UnitSummary
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UnitSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UnitSummary"
     */
    public function testUnitSummary()
    {
    }

    /**
     * Test attribute "unit_type"
     */
    public function testPropertyUnitType()
    {
    }

    /**
     * Test attribute "min_income_range"
     */
    public function testPropertyMinIncomeRange()
    {
    }

    /**
     * Test attribute "occupancy_range"
     */
    public function testPropertyOccupancyRange()
    {
    }

    /**
     * Test attribute "rent_as_percent_income_range"
     */
    public function testPropertyRentAsPercentIncomeRange()
    {
    }

    /**
     * Test attribute "rent_range"
     */
    public function testPropertyRentRange()
    {
    }

    /**
     * Test attribute "total_available"
     */
    public function testPropertyTotalAvailable()
    {
    }

    /**
     * Test attribute "area_range"
     */
    public function testPropertyAreaRange()
    {
    }

    /**
     * Test attribute "floor_range"
     */
    public function testPropertyFloorRange()
    {
    }
}
