<?php
/**
 * ApplicationMethodType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bloom API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * ApplicationMethodType Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApplicationMethodType
{
    /**
     * Possible values of this enum
     */
    const INTERNAL = 'Internal';
const FILE_DOWNLOAD = 'FileDownload';
const EXTERNAL_LINK = 'ExternalLink';
const PAPER_PICKUP = 'PaperPickup';
const PO_BOX = 'POBox';
const LEASING_AGENT = 'LeasingAgent';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INTERNAL,
self::FILE_DOWNLOAD,
self::EXTERNAL_LINK,
self::PAPER_PICKUP,
self::PO_BOX,
self::LEASING_AGENT,        ];
    }
}
