<?php
/**
 * WhatToExpect
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bloom API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * WhatToExpect Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WhatToExpect implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'WhatToExpect';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'applicants_will_be_contacted' => 'string',
'all_info_will_be_verified' => 'string',
'be_prepared_if_chosen' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'applicants_will_be_contacted' => null,
'all_info_will_be_verified' => null,
'be_prepared_if_chosen' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'applicants_will_be_contacted' => 'applicantsWillBeContacted',
'all_info_will_be_verified' => 'allInfoWillBeVerified',
'be_prepared_if_chosen' => 'bePreparedIfChosen'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'applicants_will_be_contacted' => 'setApplicantsWillBeContacted',
'all_info_will_be_verified' => 'setAllInfoWillBeVerified',
'be_prepared_if_chosen' => 'setBePreparedIfChosen'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'applicants_will_be_contacted' => 'getApplicantsWillBeContacted',
'all_info_will_be_verified' => 'getAllInfoWillBeVerified',
'be_prepared_if_chosen' => 'getBePreparedIfChosen'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['applicants_will_be_contacted'] = isset($data['applicants_will_be_contacted']) ? $data['applicants_will_be_contacted'] : null;
        $this->container['all_info_will_be_verified'] = isset($data['all_info_will_be_verified']) ? $data['all_info_will_be_verified'] : null;
        $this->container['be_prepared_if_chosen'] = isset($data['be_prepared_if_chosen']) ? $data['be_prepared_if_chosen'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['applicants_will_be_contacted'] === null) {
            $invalidProperties[] = "'applicants_will_be_contacted' can't be null";
        }
        if ($this->container['all_info_will_be_verified'] === null) {
            $invalidProperties[] = "'all_info_will_be_verified' can't be null";
        }
        if ($this->container['be_prepared_if_chosen'] === null) {
            $invalidProperties[] = "'be_prepared_if_chosen' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets applicants_will_be_contacted
     *
     * @return string
     */
    public function getApplicantsWillBeContacted()
    {
        return $this->container['applicants_will_be_contacted'];
    }

    /**
     * Sets applicants_will_be_contacted
     *
     * @param string $applicants_will_be_contacted applicants_will_be_contacted
     *
     * @return $this
     */
    public function setApplicantsWillBeContacted($applicants_will_be_contacted)
    {
        $this->container['applicants_will_be_contacted'] = $applicants_will_be_contacted;

        return $this;
    }

    /**
     * Gets all_info_will_be_verified
     *
     * @return string
     */
    public function getAllInfoWillBeVerified()
    {
        return $this->container['all_info_will_be_verified'];
    }

    /**
     * Sets all_info_will_be_verified
     *
     * @param string $all_info_will_be_verified all_info_will_be_verified
     *
     * @return $this
     */
    public function setAllInfoWillBeVerified($all_info_will_be_verified)
    {
        $this->container['all_info_will_be_verified'] = $all_info_will_be_verified;

        return $this;
    }

    /**
     * Gets be_prepared_if_chosen
     *
     * @return string
     */
    public function getBePreparedIfChosen()
    {
        return $this->container['be_prepared_if_chosen'];
    }

    /**
     * Sets be_prepared_if_chosen
     *
     * @param string $be_prepared_if_chosen be_prepared_if_chosen
     *
     * @return $this
     */
    public function setBePreparedIfChosen($be_prepared_if_chosen)
    {
        $this->container['be_prepared_if_chosen'] = $be_prepared_if_chosen;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
